//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElectoralRoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblElectoralRoll()
        {
            this.tblVoters = new HashSet<tblVoter>();
        }
    
        public int Id { get; set; }
        public int RevisionYear { get; set; }
        public Nullable<System.DateTime> QualifyingDate { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string RevisionType { get; set; }
        public string RollSummary { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoter> tblVoters { get; set; }
    }
}
