//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParliamentConstituency
    {
        public long ParliamentConstituencyId { get; set; }
        public int StateId { get; set; }
        public int PCNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> ReservedFor { get; set; }
    
        public virtual tblState tblState { get; set; }
    }
}
