//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssemblyConstituency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssemblyConstituency()
        {
            this.tblCommunities = new HashSet<tblCommunity>();
            this.tblPollingStations = new HashSet<tblPollingStation>();
            this.tblVoters = new HashSet<tblVoter>();
        }
    
        public int ACNo { get; set; }
        public int DistrictId { get; set; }
        public int PCNo { get; set; }
        public string Name { get; set; }
        public string NameTE { get; set; }
        public Nullable<int> ReservedFor { get; set; }
    
        public virtual tblParliamentConstituency tblParliamentConstituency { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommunity> tblCommunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPollingStation> tblPollingStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoter> tblVoters { get; set; }
    }
}
