//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssemblyConstituency
    {
        public long AssemblyConstituencyId { get; set; }
        public long DistrictId { get; set; }
        public long ParliamentConstituencyId { get; set; }
        public int ACNo { get; set; }
        public string Name { get; set; }
        public string NameTE { get; set; }
        public Nullable<int> ReservedFor { get; set; }
    
        public virtual tblDistrict tblDistrict { get; set; }
    }
}
