//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoterExt
    {
        public long Id { get; set; }
        public long VoterId { get; set; }
        public bool IsAccurate { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public string HeadMobileNo { get; set; }
        public string AltMobileNo { get; set; }
        public string WhatsAppNo { get; set; }
        public Nullable<int> SubCasteId { get; set; }
        public Nullable<int> PoliticalPartyId { get; set; }
        public Nullable<bool> IsNRIVote { get; set; }
        public string GeoTagInfo { get; set; }
        public string Notes { get; set; }
        public string Remarks { get; set; }
        public int VerifyStatus { get; set; }
        public bool VerifyAuthorizeStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CommunityId { get; set; }
        public Nullable<long> OldCommunityId { get; set; }
    
        public virtual tblVoter tblVoter { get; set; }
        public virtual tblCommunity tblCommunity { get; set; }
        public virtual tblCommunity tblCommunity1 { get; set; }
    }
}
