//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoterRequestExt
    {
        public long Id { get; set; }
        public long VoterRequestId { get; set; }
        public int ReqAttrId { get; set; }
        public string ReqAttrValue { get; set; }
        public string PreviousValue { get; set; }
    
        public virtual tblRequestAttribute tblRequestAttribute { get; set; }
        public virtual tblVoterRequest tblVoterRequest { get; set; }
    }
}
