//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectoralApp.BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoterDemo
    {
        public long Id { get; set; }
        public int ERId { get; set; }
        public int ACNo { get; set; }
        public string EPICNo { get; set; }
        public int SerialNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Relation { get; set; }
        public string RelationName { get; set; }
        public string RelationEPICNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public int PartNo { get; set; }
        public Nullable<int> PSSId { get; set; }
        public string WardNo { get; set; }
        public string MobileNo { get; set; }
        public string DoubleMetaphone { get; set; }
        public string DoubleMetaphone1 { get; set; }
    }
}
